name: Update badges

on:
  workflow_dispatch:

jobs:
  update-credly-data:
    name: Update Json data with badges
    runs-on: ubuntu-latest
    steps:
      - name: Credly data - Hugo
        uses: pemtajo/badge-readme@main
        with:
          GH_TOKEN: ${{ secrets.CREDLY_TOKEN }}
          REPOSITORY: ShinHeeEul/ShinHeeEul
          CREDLY_USER: ${{ secrets.CREDLY_USER }}
          CREDLY_DIR: data/credly.json
          BADGE_SIZE: 256
