# GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # or any other version you want to use
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config ShinHeeEul github-actions
          git config sheshe7015@naver.com github-actions@github.com
          git add -A .
          git commit -m "generated"
          git push
